# services/tag_catalog.py
from __future__ import annotations

TAG_CATALOG: dict[str, list[str]] = {
    "Comida": [
        "Café / Bebidas",
        "Postres",
        "Panadería",
        "Comida rápida",
        "Almuerzos / Menú del día",
        "Saludable",
        "Vegano / Vegetariano",
        "Catering / Eventos",
        "Domicilios",
        "Gourmet / Artesanal",
    ],
    "Moda": [
        "Ropa femenina",
        "Ropa masculina",
        "Ropa infantil",
        "Calzado",
        "Accesorios",
        "Joyas / Bisutería",
        "Bolsos",
        "Moda sostenible",
        "Personalizado / A medida",
        "Ropa deportiva",
    ],
    "Servicios": [
        "Domicilios / Mensajería",
        "Reparaciones",
        "Mantenimiento",
        "Limpieza",
        "Belleza / Estética",
        "Fotografía / Video",
        "Eventos / Decoración",
        "Asesorías / Consultoría",
        "Transporte",
        "Servicios para mascotas",
    ],
    "Tecnología": [
        "Soporte técnico",
        "Mantenimiento PC",
        "Celulares / Tablets",
        "Redes / WiFi",
        "Desarrollo web",
        "Diseño gráfico",
        "Marketing digital",
        "Tiendas online",
        "Automatización",
        "Seguridad / Cámaras",
    ],
    "Hogar": [
        "Decoración",
        "Muebles",
        "Organización",
        "Jardinería",
        "Iluminación",
        "Ferretería / Herramientas",
        "Textiles (cortinas, sábanas)",
        "Cocina (utensilios)",
        "Aromas / Velas",
        "Productos ecológicos",
    ],
    "Salud": [
        "Terapias",
        "Psicología / Coaching",
        "Nutrición",
        "Medicina alternativa",
        "Entrenamiento / Fitness",
        "Estética",
        "Masajes",
        "Cuidado personal",
        "Productos naturales",
        "Rehabilitación",
    ],
    "Educación": [
        "Tutorías",
        "Idiomas",
        "Cursos online",
        "Clases particulares",
        "Música",
        "Refuerzo escolar",
        "Preparación exámenes",
        "Tecnología / Programación",
        "Talleres para niños",
        "Material educativo",
    ],
    "Arte": [
        "Ilustración",
        "Pintura",
        "Artesanías",
        "Manualidades",
        "Personalizados",
        "Papelería creativa",
        "Joyería artesanal",
        "Arte digital",
        "Regalos",
        "Decoración artística",
    ],
}

def tags_for_category(category: str | None) -> list[str]:
    """Devuelve las opciones de tags para una categoría."""
    if not category:
        return []
    return TAG_CATALOG.get(category, [])
